### ISSUE TITLE
Add optional Dragable to LongPressDragable

### ISSUE THREAD

**Issue by apps-transround** [hanshengchiu/reorderables#10]
In certain cases immediate drag is preferred by users. Please add option to select Dragable or LongPressDragable while encapsulating children.
Thanks.

**Comment by apps-transround** [comment]
That was quick, thanks.

**Comment by Nico04** [comment]
Hi, in my understanding, the needsLongPressDraggable flag is only implemented in the Wrap Widget, I'd love to have it on the Column one too, is it possible please ?
