### ISSUE TITLE
Null-safety support PR

### ISSUE THREAD

**Issue by nyarian** [hanshengchiu/reorderables#104]
There is a null-safety migrated fork of the current master branch: https://github.com/Three-Horsemen-of-Software-Engineering/reorderables/tree/beta/nullsafety_migration

It would be nice if it could be merged into a separate branch in this repository, but the only option repositories can interact here (afaik) is PRs across forks, and a separate target branch is needed for null-safety support, because it's not yet the time for the master branch to be targeted.

**Comment by hanshengchiu** [comment]
Closing as nullsafety is being addressed in master
