### ISSUE TITLE
ReorderableWrap drag background color is red

### ISSUE THREAD

**Issue by linjonathan2001** [hanshengchiu/reorderables#107]
How do I change it to Colors.transparent?

I've tried Theme(data: ThemeData(canvasColor: Colors.transparent, child: ReorderableWrap()))

**Comment by linjonathan2001** [comment]
I've tried all of the ThemeData values:
backgroundColor: Colors.transparent,
primaryColor: Colors.transparent,
primaryColorLight: Colors.transparent,
primaryColorDark: Colors.transparent,
accentColor: Colors.transparent,
canvasColor: Colors.transparent,
shadowColor: Colors.transparent,
scaffoldBackgroundColor: Colors.transparent,
bottomAppBarColor: Colors.transparent,
cardColor: Colors.transparent,
dividerColor: Colors.transparent,
focusColor: Colors.transparent,
hoverColor: Colors.transparent,
highlightColor: Colors.transparent,
splashColor: Colors.transparent,
selectedRowColor: Colors.transparent,
unselectedWidgetColor: Colors.transparent,
disabledColor: Colors.transparent,
buttonColor: Colors.transparent,
secondaryHeaderColor: Colors.transparent,
dialogBackgroundColor: Colors.transparent,
indicatorColor: Colors.transparent,
hintColor: Colors.transparent,
errorColor: Colors.transparent,
toggleableActiveColor: Colors.transparent

None of them change the red background :(

**Comment by datdefboi** [comment]
Hi, i've fixed that with this snippet:
```dart
buildDraggableFeedback:
          (BuildContext context, BoxConstraints constraints, Widget child) {
        return Transform(
          transform: Matrix4.rotationZ(0),
          alignment: FractionalOffset.topLeft,
          child: ConstrainedBox(constraints: constraints, child: child),
        );
      },
```

**Comment by linjonathan2001** [comment]
> Hi, i've fixed that with this snippet:
> 
> ```dart
> buildDraggableFeedback:
>           (BuildContext context, BoxConstraints constraints, Widget child) {
>         return Transform(
>           transform: Matrix4.rotationZ(0),
>           alignment: FractionalOffset.topLeft,
>           child: ConstrainedBox(constraints: constraints, child: child),
>         );
>       },
> ```

Unfortunately, this did not work. It made all text in the widget red while dragging. 

Regardless, the issue seems to have resolved itself because I don't see the red background anymore even though I haven't changed the code.
