### ISSUE TITLE
Can we please get another release?

### ISSUE THREAD

**Issue by diegotori** [hanshengchiu/reorderables#110]
@hanshengchiu as the title states, seeing that you recently merged in null-safety changes, is there any chance that you can please deploy another release to pub.dev, so that folks such as myself can upgrade to null-safety?

Thanks in advance.

**Comment by hanshengchiu** [comment]
@diegotori it seems null-safety is a breaking change? According to https://dart.dev/null-safety/migration-guide

**Comment by diegotori** [comment]
It's supposed to be. Lots of other developers have been offering major release versions supporting null-safety. In this case, I propose that it be released as a version `1.0.0` for example, so that it doesn't affect the existing releases.

**Comment by diegotori** [comment]
@hanshengchiu any update on this, since this is one of the few dependencies preventing me from adopting sound null-safety in my app. Thank you in advance.

**Comment by Arcturus5404** [comment]
Bump!

**Comment by hanshengchiu** [comment]
will do, but just need to sort out few things this week

**Comment by hanshengchiu** [comment]
any way I can setup automated release whenever there's a new pull request merged?

**Comment by Arcturus5404** [comment]
Thanks @hanshengchiu !

**Comment by diegotori** [comment]
@hanshengchiu To my knowledge, there's no easy way to automate the deployment of new pub.dev releases.

Alternatively, you can designate people to deploy new releases on your behalf using `pub uploader` and that person's email address. Also, you can designate other folks as maintainers in addition to yourself so that others can approve/merge code on your behalf.

**Comment by hanshengchiu** [comment]
> @hanshengchiu To my knowledge, there's no easy way to automate the deployment of new pub.dev releases.
> 
> Alternatively, you can designate people to deploy new releases on your behalf using `pub uploader` and that person's email address. Also, you can designate other folks as Project Maintainers in addition to yourself so that others can approve/merge code on your behalf.

But the building process must still happen in Android Studio?
I remember asking some if he could help, however people have priorities.

**Comment by diegotori** [comment]
The build process can happen through command line actually. I mean if you need someone to act as an uploader, I'm available.

**Comment by hanshengchiu** [comment]
@diegotori That'd be great. An uploader invitation and a collaborator invitation should have been sent to your email.

**Comment by diegotori** [comment]
@hanshengchiu received them and accepted them. I'm gonna try to release a new build. However, I need to know what version to release it under? Is this a `1.0.0` release, or more of a `0.4.0` release? Once you let me know, I'll update the version commit and push the change. Then publish it to pub.dev.

**Comment by diegotori** [comment]
@hanshengchiu I created a PR to address all of the remaining issues before deploying `0.4.0`.

**Comment by Arcturus5404** [comment]
If the changes are breaking, consider updating to 1.0.0, otherwise, 0.4.0 sounds fine?

**Comment by hanshengchiu** [comment]
> @hanshengchiu received them and accepted them. I'm gonna try to release a new build. However, I need to know what version to release it under? Is this a `1.0.0` release, or more of a `0.4.0` release? Once you let me know, I'll update the version, commit and push the change. Then publish it to pub.dev.

Merged. Let's go with 0.4.

**Comment by diegotori** [comment]
Roger.

**Comment by diegotori** [comment]
Version `0.4.0` should already be live on pub.dev with Null-Safety in tow.

**Comment by hanshengchiu** [comment]
Thumbs up and huge thanks to @diegotori

**Comment by Arcturus5404** [comment]
Thanks guys! Much appreciated!!
