### ISSUE TITLE
Reordering index to 0 instead of 1 when dragging above expanded FlexibleSpaceBar

### ISSUE THREAD

**Issue by davidBarbieri** [hanshengchiu/reorderables#12]
HI! Thanks again for the grat package.

I'm aving a little issue when i'm dragging items to the top with an expanded FlexibleSpaceBar:
I drag an item from any position to the top, if i stop dragging on the topmost tile, i'm correctly show the preview in the right place, and the TO index is correctly 1, but if i keep dragging on top of the Flexible bar, the preview tile animates sliding again above itselft (still appearing at the right place) but the TO index is 0

This is the result of the draggin to top, the first two i stop on the tile, the then is when i drag all the way up

```
I/flutter ( 6130): from: 2 -> to 1
I/flutter ( 6130): from: 2 -> to 1
I/flutter ( 6130): from: 3 -> to 0
I/flutter ( 6130): from: 2 -> to 0
I/flutter ( 6130): from: 3 -> to 0
```

At the moment i fixed it by setting the index back to 1 if i see 0 in my code.
I tried it only in my code, so maybe it's not a plugin problem.

Thanks!

David

**Comment by hanshengchiu** [comment]
can show an example?

**Comment by davidBarbieri** [comment]
I think it was actually an implementation problem, i have two nested lists rendered recursively, and didn't tell the inner list to render as normal ListView(within a tile of the parent list) , so there were 2 Reorderable Sliver lists one inside the other.
Works like a charm now.

**Comment by hanshengchiu** [comment]
Today's update should let you nest multiple lists without problem, though I didn't verify it.
