### ISSUE TITLE
Is it possible to activate dragging immediately, not on long press?

### ISSUE THREAD

**Issue by alexursul** [hanshengchiu/reorderables#126]
Is it possible to activate dragging immediately, not on long press? It would be super nice to have a possibility to reduce the time before an item is activated and become draggable.

**Comment by cmsong-shina** [comment]
Well, maybe. try below

```dart
ReorderableWrap(
  needsLongPressDraggable: false,
 ...
)
```

**Comment by metelskiwiktor** [comment]
> Well, maybe. try below
> 
> ```dart
> ReorderableWrap(
>   needsLongPressDraggable: false,
>  ...
> )
> ```

Works perfectly, thanks

**Comment by kenan2002** [comment]
Is there a similar config for ReorderableSliverList?
