### ISSUE TITLE
Project breaks for Flutter 1.5.9

### ISSUE THREAD

**Issue by brunocalou** [hanshengchiu/reorderables#13]
Using the latest flutter version, the library breaks due to flutter changes on Diagnostics related features.

The error message is:

Compiler message:
file:///Users/brunocalou/Development/flutter/.pub-cache/hosted/pub.dartlang.org/reorderables-0.2.7/lib/src/widgets/reorderable_sliver.dart:76:16: Error: The argument type 'String' can't be assigned to the parameter type 'DiagnosticsNode'.
 - 'DiagnosticsNode' is from 'package:flutter/src/foundation/diagnostics.dart' ('file:///Users/brunocalou/Development/flutter/packages/flutter/lib/src/foundation/diagnostics.dart').
Try changing the type of the parameter, or casting the argument to 'DiagnosticsNode'.
      context: 'building',
               ^
file:///Users/brunocalou/Development/flutter/.pub-cache/hosted/pub.dartlang.org/reorderables-0.2.7/lib/src/rendering/tabluar_flex.dart:927:26: Error: The argument type 'String' can't be assigned to the parameter type 'List<DiagnosticsNode>'.
 - 'List' is from 'dart:core'.
 - 'DiagnosticsNode' is from 'package:flutter/src/foundation/diagnostics.dart' ('file:///Users/brunocalou/Development/flutter/packages/flutter/lib/src/foundation/diagnostics.dart').
Try changing the type of the parameter, or casting the argument to 'List<DiagnosticsNode>'.
          overflowHints: debugOverflowHints);

### Flutter doctor output

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.5.9-pre.258, on Mac OS X 10.14.4 18E226, locale en-BR)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.3)
[✓] IntelliJ IDEA Community Edition (version 2018.3.5)
[✓] VS Code (version 1.27.2)
[✓] Connected device (1 available)

**Comment by hanshengchiu** [comment]
I'm using the latest flutter release. The version you use doesn't seem to be official yet.
[√] Flutter (Channel beta, v1.5.4-hotfix.2, on Microsoft Windows

**Comment by Nico04** [comment]
I've got similar issue with last stable flutter and plugin v0.2.10.
plugin v0.2.9 works fine.

**Comment by hanshengchiu** [comment]
What's your flutter version? 
Mine is [√] Flutter (Channel beta, v1.6.3, on Microsoft Windows [Version 10.0.17763.529], locale en-US) and 0.2.10 works fine.

**Comment by Nico04** [comment]
I'm on the latest stable version :
[√] Flutter (Channel stable, v1.5.4-hotfix.2, on Microsoft Windows [Version 10.0.17763.529], locale en-GB)

**Comment by hanshengchiu** [comment]
I think this is an incompatibility between flutter v1.5.4-hotfix.2 and newer versions. OP had the same issue with what I have with v1.6.3. Back then the change to FlutterErrorDetails hadn't been push forward to beta or stable channel. But now it has.
However your issue is the other way round. When a newer version of flutter is released on stable channel, v0.2.10 should work.

**Comment by Nico04** [comment]
> However your issue is the other way round. When a newer version of flutter is released on stable channel, v0.2.10 should work.
OK, I'll wait until september for the next release to update your package. Thanks.

**Comment by energynumbers** [comment]
Quoting from https://github.com/flutter/flutter/issues/31962

> If you package isn't trying to act like it is part of package:flutter then you should consider whether FlutterError and FlutterErrorDetails are classes you should be using. You might be confusing your users more than helping them by making your errors look like they are coming from the framework instead of from your library. For example the documentation for FlutterError says it is an "Error class used to report Flutter-specific assertion failures and contract violations."

> I'm interested in understanding how you are using FlutterErrorDetails in your user code. What are you looking to accomplish using the class? In general this wasn't a class we expected users to use.

**Comment by hanshengchiu** [comment]
Thanks for the info. In that case the two classes shouldn't have been exported. However the two classes are available as long as you include materials.dart or foundations.dart and the documentation doesn't say FlutterErrorDetails is Flutter-specific... I will remove it.

**Comment by hanshengchiu** [comment]
v0.2.12
