### ISSUE TITLE
ReorderableWrap  cannot move any other indexed item to index 0. All other operations work.

### ISSUE THREAD

**Issue by srihariash999** [hanshengchiu/reorderables#135]
In a reorderable wrap. No element further down the list can be placed at index 0. They come upto index 1 and not any further.

If you try moving items from top to any place at bottom, it works absolutely fine. But cannot move any item from botttom to absolute top.

**Comment by Suhrt** [comment]
I had similar issue, correcting the index fixed things for me

```
onReorder: (int oldIndex, int newIndex) {
        setState(() {
          if (oldIndex < newIndex) {
            newIndex -= 1;
          }
          final int item = _items.removeAt(oldIndex);
          _items.insert(newIndex, item);
        });
      },
```

**Comment by srihariash999** [comment]
I think this workaround is fine for now. As the author is not active. Thanks @Suhrt

**Comment by diegotori** [comment]
@srihariash999 can you create a reproducible example for this issue, so that either myself or @hanshengchiu can review? Thanks in advance.

**Comment by srihariash999** [comment]
@diegotori i can provide it over this weekend.
