### ISSUE TITLE
Support for Cupernito

### ISSUE THREAD

**Issue by remygautron** [hanshengchiu/reorderables#15]
Hello,

The plugin doesn't work if isn't a MaterialApp.

Maybe you can add a support for Cupernito or a trick ?

Thanks

**Comment by hanshengchiu** [comment]
I've use material design only. Did you just replace MaterialApp with CupertinoApp?

**Comment by remygautron** [comment]
Yes and doesn't work (assert error)

**Comment by hanshengchiu** [comment]
v0.2.9
