### ISSUE TITLE
PrimaryScrollController.of() was called with a context that does not contain a PrimaryScrollController widget thrown after flutter upgrade

### ISSUE THREAD

**Issue by Orlyga01** [hanshengchiu/reorderables#167]
Hi,
I've just upgraded to Flutter 3.6.0-4.0.pre.2 • channel master
After upgrade I get this message:
`I/flutter ( 8048):   _ReorderableFlexContent(dirty, dependencies: [PrimaryScrollController], state:
I/flutter ( 8048): _ReorderableFlexContentState#46973(tickers: tracking 2 tickers))
I/flutter ( 8048): 
I/flutter ( 8048): The relevant error-causing widget was:
I/flutter ( 8048):   _ReorderableFlexContent
I/flutter ( 8048):   _ReorderableFlexContent:file:///C:/Users/oreznik/AppData/Local/Pub/Cache/hosted/pub.dev/reorderables-0.5.1/lib/src/widgets/reorderable_flex.dart:139:16
I/flutter ( 8048): 
I/flutter ( 8048): When the exception was thrown, this was the stack:
I/flutter ( 8048): #0      PrimaryScrollController.of.<anonymous closure> (package:flutter/src/widgets/primary_scroll_controller.dart:158:9)
I/flutter ( 8048): #1      PrimaryScrollController.of (package:flutter/src/widgets/primary_scroll_controller.dart:170:6)
I/flutter ( 8048): #2      _ReorderableFlexContentState.build (package:reorderables/src/widgets/reorderable_flex.dart:885:33)`

I was using   reorderables: ^0.5.1 and ^0.5.0
flutter doctor is fine
This is my code:

`final ScrollController reorderScrollController = ScrollController();
List<Widget> _row=[....];
  @override
  Widget build(BuildContext context) {
 return ReorderableColumn(
      children: _rows,
      onReorder: _onReorder,
//Error is not changed if I add this parameter
      scrollController: reorderScrollController ,
    );
}`

**Comment by derteufelqwe** [comment]
This is most likely due to some changes flutter did to scrolling.
You can solve that issue by providing a `PrimaryScrollController` up in the widget tree.

**Comment by luccasclezar** [comment]
With Flutter 3.7 released, `PrimaryScrollController.of` is only used when a PrimaryScrollController is known to be present in the widget tree. The right method to return a nullable is now `PrimaryScrollController.maybeOf`.

It seems `PrimaryScrollController.of` is only used 5 times in the whole plugin. Should be easy to fix.
