### ISSUE TITLE
Scrollable.of() was called with a context that does not contain a Scrollable widget.

### ISSUE THREAD

**Issue by kmarellapudi** [hanshengchiu/reorderables#175]
No Scrollable widget ancestor could be found starting from the context that was passed to Scrollable.of(). This can happen because you are using a widget that looks for a Scrollable ancestor, but no such ancestor exists.
The context used was:
  Slidable(dirty, state: SlidableState#e1008(lifecycle state: initialized, tickers: tracking 1 ticker))

When the exception was thrown, this was the stack: 
#0      Scrollable.of.<anonymous closure> (package:flutter/src/widgets/scrollable.dart:336:9)
#1      Scrollable.of (package:flutter/src/widgets/scrollable.dart:348:6)
#2      SlidableState._addScrollingNotifierListener (package:flutter_slidable/src/widgets/slidable.dart:663:36)
#3      SlidableState.didChangeDependencies (package:flutter_slidable/src/widgets/slidable.dart:648:5)
#4      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5119:11)
#5      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4944:5)
...     Normal element mounting (181 frames)
#186    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953:16)
#187    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6512:36)
#188    Element.updateChild (package:flutter/src/widgets/framework.dart:3682:18)
#189    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:6041:32)
#190    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6537:17)
#191    Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#192    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#193    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5133:11)

**Comment by felipecastrosales** [comment]
Same issue here. Any news, @hanshengchiu?

**Comment by diegotori** [comment]
@kmarellapudi please provide a reproducible example of this issue, so that I can further debug it.

Thanks in advance.

**Comment by Bikuta-victor1** [comment]
Is there any fix for this yet ?

**Comment by decisionslab2** [comment]
we have been facing the same issue. Any updates?

**Comment by felipecastrosales** [comment]
I had this problem. 

But now, using `Flutter 3.7.5` and `reorderables 0.6.0` I don't have it anymore. 

edit: commenting to give the feedback and to see if it helps you, @decisionslab2.

**Comment by decisionslab2** [comment]
Great. After updating it Flutter 3.7.5 and reorderables 0.6.0 it worked.

**Comment by felipecastrosales** [comment]
I think we can close this question, @kmarellapudi and @hanshengchiu.
