### ISSUE TITLE
Allow to choose which row can be ordered

### ISSUE THREAD

**Issue by unamed000** [hanshengchiu/reorderables#36]
In my Flutter app, i have a functionality which let the user order activities in days, the problem is the package doesn't have any functionality to prevent ordering such a row (in this case it's Days rows).

Example:
--- Day 1 ---
--Activity 1--
--Activity 2--
--Activity 3--
--- Day 2 ---
--Activity 4--
--Activity 5--
--Activity 6--

Can we have a workaround for this one? 

Thanks.

**Comment by hanshengchiu** [comment]
v0.3.1
