### ISSUE TITLE
Callback for start reordering

### ISSUE THREAD

**Issue by rablexxx** [hanshengchiu/reorderables#37]
Hello!
Is there a way to detect start of reordering? Maybe it would be useful to add a callback function for this?
Thanks in advance

**Comment by hanshengchiu** [comment]
why do you need to know the start of reordering?

**Comment by rablexxx** [comment]
I need to update other parts of UI (set some flags, stop animations, etc.)

**Comment by truthmast** [comment]
Can this be merged into master? I'm using my own fork for now because of this requirement.
