### ISSUE TITLE
Disabling disabling order/drag for certain tiles.

### ISSUE THREAD

**Issue by jimmyff** [hanshengchiu/reorderables#43]
I'm using this to allow the ordering of photographs in my app. I have a 3x2 grid of photo tiles, I'm using the `ReorderableWrap` widget. I fill the empty photo tiles with a tile with tile that contains a `+` icon, when tapped starts the upload new photo workflow. I would like it so these empty tiles cannot be reordered.  It's would be only possible to reorder the tiles that are populated with photographs. Is there anyway I could achieve this?

One possible implementation: Tiles could all have a `DraggableWidget` parent which has a `child` property and an `enabled` property? 

This request is similar yet not quite the same as: https://github.com/hanshengchiu/reorderables/issues/39

I've also tried your suggestion https://github.com/hanshengchiu/reorderables/issues/31 of using the footer/header but this doesn't work as I have numerous items I want to none-draggable.

**Comment by g123k** [comment]
Hello,

I have created a PR for this use-case.
If you want to test it: https://github.com/hanshengchiu/reorderables/pull/45

**Comment by hanshengchiu** [comment]
v0.3.1

**Comment by dinbtechit** [comment]
Thanks for the great feature. I was looking for it; for a long time. Just curious is there an way to prevent dragging the `ReorderableWidget` `reorderable: false` beyond the disabled items?

Adding the below logic in `_onReorder` seems to prevent reordering beyond the disabled indexes. Is there a way to disabled the drag-able animation as well?

```
 Widget build(BuildContext context) {
    void _onReorder(int oldIndex, int newIndex) {
      setState(() {
        if (newIndex < 7) { //Prevent reordering an beyond the non-reorderable items.
          Widget row = _tiles.removeAt(oldIndex);
          _tiles.insert(newIndex, row);
        }
      });
    }
```
![IlDaZ6nleO](https://user-images.githubusercontent.com/17984781/77261009-17cf0d80-6c6a-11ea-9f35-ef2a943d110a.gif)
