### ISSUE TITLE
ScrollController attached to multiple scroll views

### ISSUE THREAD

**Issue by CoderXiaoming** [hanshengchiu/reorderables#44]
![Snip20191112_2](https://user-images.githubusercontent.com/23111683/68661523-0d8f5b00-0576-11ea-9c5a-8962035f8396.png)
![Snip20191112_3](https://user-images.githubusercontent.com/23111683/68661532-13853c00-0576-11ea-8f67-91ce6bcb0b16.png)

**Comment by hanshengchiu** [comment]
could you provide test code?

**Comment by saisantosh2095** [comment]
If you are using a **ListView** or a **GridView** along with **"ReorderableWrap"**, specify controllers for the other ListViews or GridViews taht solved the issue in my case.

**Comment by JosephNK** [comment]
@saisantosh2095 I solved it in the way you told me. Thank you. :)

**Comment by talski** [comment]
example code still throw this error at **"ReorderableWrap"**
