### ISSUE TITLE
Option to drag item outside of list to an external component to perform an action

### ISSUE THREAD

**Issue by baughmann** [hanshengchiu/reorderables#50]
I'm new to Flutter and to this project, but Id like to look into adding an optional feature to this library. It would be useful to the user to drag items outside of the list to perform some action on them, such as dragging them to a "trash can" or something.

I'll clone this library and start playing around with it, but it would be nice if someone could point me in the right direction to start exploring. Any suggestions off of the top of your head where to look to add this feature?

**Comment by andreddie81** [comment]
looking into the same problem and missing the exact same functionality, hope the author of the library responds.

**Comment by hanshengchiu** [comment]
Feel free to submit PR. Maybe what you need is just simple drag and drop.

**Comment by mdkess** [comment]
One thing I've done is use a DragTarget<int> to drag things outside. You'll get the index within the reorderable, and it seems to work well.
