### ISSUE TITLE
scrollController not working

### ISSUE THREAD

**Issue by ramojus** [hanshengchiu/reorderables#57]
When I add a scrollController, I get RenderFlex overflowed which doesn't happen without scrollController and when I try to do something with controller I get this error:
"Unhandled Exception: 'package:flutter/src/widgets/scroll_controller.dart': Failed assertion: line 110 pos 12: '_positions.isNotEmpty': ScrollController not attached to any scroll views."

**Comment by hanshengchiu** [comment]
Could you try v0.3.1 or provide some test code?
