### ISSUE TITLE
Error while adding library.

### ISSUE THREAD

**Issue by achinverma** [hanshengchiu/reorderables#59]
I am getting the below error. 

Version :
reorderables: ^0.2.12

Compiler message:                                                       
../../../.pub-cache/hosted/pub.dartlang.org/reorderables-0.2.12/lib/src/widgets/reorderable_flex.dart:727:18: Error: The argument type 'Null Function(Key)' can't be assigned to the parameter type 'void Function(Object)'.
 - 'Key' is from 'package:flutter/src/foundation/key.dart' ('../../../flutter-sdk/packages/flutter/lib/src/foundation/key.dart').
 - 'Object' is from 'dart:core'.                                        
        onLeave: (Key leaving) {},                                      
                 ^                                                      
../../../.pub-cache/hosted/pub.dartlang.org/reorderables-0.2.12/lib/src/widgets/reorderable_wrap.dart:951:18: Error: The argument type 'Null Function(int)' can't be assigned to the parameter type 'void Function(Object)'.
 - 'Object' is from 'dart:core'.                                        
        onLeave: (int leaving) {},                                      
                 ^                                                      
../../../.pub-cache/hosted/pub.dartlang.org/reorderables-0.2.12/lib/src/widgets/reorderable_wrap.dart:957:18: Error: The argument type 'Null Function(int)' can't be assigned to the parameter type 'void Function(Object)'.
 - 'Object' is from 'dart:core'.                                        
        onLeave: (int leaving) {},                                      
                 ^                                                      
../../../.pub-cache/hosted/pub.dartlang.org/reorderables-0.2.12/lib/src/widgets/reorderable_sliver.dart:842:18: Error: The argument type 'Null Function(int)' can't be assigned to the parameter type 'void Function(Object)'.
 - 'Object' is from 'dart:core'.                                        
        onLeave: (int leaving) {},                                      
                 ^                                                      
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
build failed.                                                           
                                                                        
FAILURE: Build failed with an exception.

**Comment by achinverma** [comment]
![image](https://user-images.githubusercontent.com/2811593/75447099-b4b1ca00-598e-11ea-9402-aac343a82395.png)

**Comment by Ahmadre** [comment]
@achinverma which Flutter version and channel are you using? I got similar issues

**Comment by achinverma** [comment]
@Ahmadre , I am using below.
Flutter 1.13.6-pre.32 • channel master 
Dart 2.8.0 (build 2.8.0-dev.0.0 c260e4e8da)

**Comment by Ahmadre** [comment]
Try to upgrade your master version and dart version and retry it.

**Comment by achinverma** [comment]
@Ahmadre , is it possible to fix this library issue in my flutter version. ? 
I can not upgrade during my project development.

**Comment by qwert2603** [comment]
You can fork the project, fix errors, and then use your fixed version in your project. You can depend on Github projects in pubspec.yaml.
See "Dependencies on unpublished packages" in 
https://flutter.dev/docs/development/packages-and-plugins/using-packages

**Comment by hanshengchiu** [comment]
v0.3.0
