### ISSUE TITLE
Drag customization of list items

### ISSUE THREAD

**Issue by unveloper** [hanshengchiu/reorderables#61]
Hi!

It's possible to have a class or a mixin to wrap list items which gives the ability of drag behaviour customization like:

1. enable / disable drag (already asked https://github.com/hanshengchiu/reorderables/issues/43)
2. define which widget of the list item is the draggable element (the whole item itself or a child drag handle for example)

Thanks

**Comment by hanshengchiu** [comment]
check out v0.3.1

**Comment by unveloper** [comment]
Thanks but I can't find the example for the second point, implementing a drag handle.
I mean something like this:
https://therubberduckdev.files.wordpress.com/2017/10/recyclerview-manual-drag-drop.gif?w=1100

So you can reorder an object only if long press the "hamburger icon" on the right.
