### ISSUE TITLE
Add elevation (shadow) option while dragging

### ISSUE THREAD

**Issue by dhiyaaulauliyaa** [hanshengchiu/reorderables#63]
Hi, my name is Ado, and I am using your package to develop an app.

First of all, thanks for this great plugin! This plugin has solved my problem with making a reorderable list in a sliver list. 

However, I encountered a problem when I want to change the elevation when the object is dragged. It'll be great if you can provide the option to change the elevation/shadow. 

I am looking forward to hearing from you. 

Best regards,
Ado

**Comment by dhiyaaulauliyaa** [comment]
Hello!

After surfing for a while on this repo, finally I found the solution to change the elevation when the object is dragged. I just have to make my own buildDraggableFeedback. 

Thank you!

**Comment by ElmouradiAmine** [comment]
Thank you! :)
