### ISSUE TITLE
Reorderable Wrap not working with provider package!

### ISSUE THREAD

**Issue by yati989** [hanshengchiu/reorderables#68]
I am using reorderableWrap for a list of containers with IconButtons children. In the function onPressed of IconButton, I am using a provider instance it works fine for tapping but as soon as I lift the icon up with long-press it shows me an error 
"Could not find the correct Provider<SomeWidget> above this Example Widget"
it's obviously there otherwise onTap would haven't worked itself.
Please Help!

**Comment by JulianBissekkou** [comment]
Are you using the correct context when accessing your provider?

**Comment by furkanvatandas** [comment]
Same issue with bloc, when I drag images it shows "BlocProvider.of() called with a context that does not contain a Bloc of type ImagesBloc"

**Comment by yati989** [comment]
> Are you using the correct context when accessing your provider?

That exactly what the problem was. I change the context to a widget higher in the tree and it's working fine.
